---
- hosts: develop
  user: vagrant
  tasks:
    - name: install basic pkg
      apt: name={{item}} state=installed
      sudo: yes
      with_items:
      - vim
      - git
      - zsh

    - name: pyenvをインストール
      args:
        creates: ~/.pyenv
      shell: '{{item.cmd}}'
      with_items:
        - cmd: git clone https://github.com/yyuu/pyenv.git ~/.pyenv

    - name: make
      shell: touch ~/.bash_profile

    - name: pyenv設定
      lineinfile:
        dest=~/.bash_profile
        line={{ item }}
      with_items:
        - 'export PYENV_ROOT=~/.pyenv'
        - 'export PATH=$PYENV_ROOT/bin:$PATH'
        - 'eval "$(pyenv init -)"'
        - 'export PATH="$PYENV_ROOT/versions/anaconda3-4.3.0/bin/:$PATH"'

    - name: anacondaをインストー
      args:
        creates: ~/.pyenv/versions/anaconda3-4.3.0
      shell: bash -lc "pyenv install anaconda3-4.3.0"

    - name: anaconda rehash
      args:
        creates: ~/.pyenv/versions/anaconda3-4.3.0
      shell: bash -lc "pyenv rehash"

   - name: anaconda global
      args:
        creates: ~/.pyenv/versions/anaconda3-4.3.0
      shell: bash -lc "pyenv global anaconda3-4.3.0"

    - name: counda update
      args:
        creates: ~/.pyenv/versions/anaconda3-4.3.0
      shell: bash -lc "conda update conda"

    - name: setting python2.7_pre
      shell: bash -lc "conda info -e | grep 'python2.7'; echo $?"
      register: result
      ignore_errors: True

    - name: setting python2.7
      shell: bash -lc "conda create -n python2.7 python=2.7 anaconda -y"
      when: result != '0'

    - name: setting python3.5_pre
      shell: bash -lc "conda info -e | grep 'python3.5'; echo $?"
      register: result
      ignore_errors: True

    - name: setting python3.5
      shell: bash -lc "conda create -n python3.5 python=3.5 anaconda -y"
      when: result != '0'
