# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu1604"
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.vm.hostname = "ubuntu1604"
  config.vm.network :forwarded_port, guest: 22, host: 2226, id: "ssh"
  config.vm.network :private_network, ip: "192.168.33.12", auto_config: false
  config.vm.synced_folder "./share", "/vagrant"
    
  # vagrant up, vagrant provision実行時のみ
  if ARGV[0] == "up" || ARGV[0] == "provision" then
    config.vm.provision "ansible_local" do |ansible|
      ansible.inventory_path = "./ansible/playbooks/hosts/local"
      ansible.playbook = "./ansible/playbooks/site.yml"
      ansible.limit = "all"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "16384"
    vb.customize ["modifyvm", :id, "--memory", "16384", "--cpus", "2", "--ioapic", "on"]
  end

end
