---
- hosts: develop
  roles:
    - { role: package }
    - { role: common }
    - { role: develop }
    - { role: font }
    - { role: mecab }

- hosts: develop
  become: yes
  roles:
    - { role: cmprescott.chrome }
    - { role: gantsign.intellij,
        intellij_edition: 'ultimate',
        intellij_install_dir: "/opt/jetbrains/idea-{{ intellij_edition }}-{{ intellij_version }}",
        intellij_version: '2017.2.1',
        intellij_default_maven_home: '/usr/share/maven/bin',
        intellij_default_jdk_home: '/usr/lib/jvm/default-java',
        intellij_redis_sha256sum: '136674855d26fb7f07a914eecc7236b177ef8349c23aa7811b9670da43d62ae2'}
        
    - { role: tersmitten.pycharm,
              pycharm_version: '2017.2.1',
              pycharm_install_prefix: '/opt/jetbrains'}
    - { role: clion,
              clion_version: '2017.2.1',
              clion_install_prefix: '/opt/jetbrains' }

