---
- hosts: develop
  roles:
    - { role: package }
    - { role: common }
    - { role: develop }
    - { role: font }
    - { role: mecab }

- hosts: develop
  become: yes
  roles:
    - { role: gantsign.visual-studio-code }
    - { role: cmprescott.chrome }
    - { role: gantsign.intellij,
        intellij_edition: 'ultimate',
        intellij_install_dir: "/opt/jetbrains/idea-{{ intellij_edition }}-{{ intellij_version }}",
        intellij_version: '2017.2.5',
        intellij_default_maven_home: '/usr/share/maven/bin',
        intellij_default_jdk_home: '/usr/lib/jvm/default-java',
        intellij_redis_sha256sum: 'a08ff0adfad2e8008d42e92d09696e43a70566b544db6c6f872e5b4d20436d2c'}
        
    - { role: tersmitten.pycharm,
              pycharm_version: '2017.2.3',
              pycharm_install_prefix: '/opt/jetbrains'}
    - { role: clion,
              clion_version: '2017.2.3',
              clion_install_prefix: '/opt/jetbrains' }

