---
- hosts: develop
  roles:
    - { role: package }
    - { role: common }
    - { role: develop }
    - { role: font }
    - { role: mecab }

- hosts: develop
  become: yes
  roles:
    - { role: cmprescott.chrome }
    - { role: gantsign.intellij,
        intellij_edition: 'ultimate',
        intellij_install_dir: "/opt/jetbrains/idea-{{ intellij_edition }}-{{ intellij_version }}",
        intellij_version: '2017.1.4',
        intellij_default_maven_home: '/usr/share/maven/bin',
        intellij_default_jdk_home: '/usr/lib/jvm/default-java',
        intellij_redis_sha256sum: 'dd5b65ab7c16b735e75eb698feaa46e2f0b4f2a96e18d10d6cfb0244d4722329'}
        
    - { role: tersmitten.pycharm,
              pycharm_version: '2017.1.4',
              pycharm_install_prefix: '/opt/jetbrains'}
    - { role: clion,
              clion_version: '2017.1.3',
              clion_install_prefix: '/opt/jetbrains' }

