---
- hosts: develop
  roles:
    - { role: package }
    - { role: common }
    - { role: develop }
    - { role: font }
    - { role: mecab }

- hosts: develop
  become: yes
  roles:
    - { role: gantsign.visual-studio-code }
    - { role: gantsign.intellij,
        intellij_edition: 'ultimate',
        intellij_install_dir: "/opt/jetbrains/idea-{{ intellij_edition }}-{{ intellij_version }}",
        intellij_version: '2017.3.1',
        intellij_default_maven_home: '/usr/share/maven/bin',
        intellij_default_jdk_home: '/usr/lib/jvm/default-java',
        intellij_redis_sha256sum: '48510017a099d2cfa72797c8d9224cada0a467bbdbc43f545bd94bf727150a3b'}
        
    - { role: tersmitten.pycharm,
              pycharm_version: '2017.3.1',
              pycharm_install_prefix: '/opt/jetbrains'}
    - { role: clion,
              clion_version: '2017.3',
              clion_install_prefix: '/opt/jetbrains' }

