---
galaxy_info:
  author: Prescott Chris
  description: Installs Google chrome.
  license: BSD
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - utopic
    - vivid
  - name: Debian
    versions:
    - squeeze
    - wheezy
  - name: Fedora
    versions:
    - 23
  categories:
  - networking
dependencies: []
