---
- name: bash_profileの作成
  args:
    creates: ~/.bash_profile
  shell: touch ~/.bash_profile
  
- name: pyenvをインストール
  args:
    creates: ~/.pyenv
  shell: '{{item.cmd}}'
  with_items:
    - cmd: git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    
- name: pyenv,anaconda設定
  lineinfile:
    dest=~/.bash_profile
    line={{ item }}
  with_items:
    - 'export PYENV_ROOT=~/.pyenv'
    - 'export PATH=$PYENV_ROOT/bin:$PATH'
    - 'eval "$(pyenv init -)"'
    - 'export PATH="$PYENV_ROOT/versions/anaconda3-4.3.1/bin/:$PATH"'

- name: anacondaをインストール
  args:
    creates: ~/.pyenv/versions/anaconda3-4.3.1
  shell: bash -lc "pyenv install anaconda3-4.3.1"
 
- name: anaconda rehash
  args:
    creates: ~/.pyenv/versions/anaconda3-4.3.1
  shell: bash -lc "pyenv rehash"
  
- name: anaconda global
  args:
    creates: ~/.pyenv/versions/anaconda3-4.3.1
  shell: bash -lc "pyenv global anaconda3-4.3.1"
  
- name: anaconda update
  args:
    creates: ~/.pyenv/versions/anaconda3-4.3.1
  shell: bash -lc "conda update conda"

- name: python2.7インストール可否チェック
  shell: bash -lc "conda info -e | grep 'python2.7'"
  register: result
  failed_when: result.rc not in [0, 1]

- name: python2.7インストール
  shell: bash -lc "conda create -n python2.7 python=2.7 anaconda -y"
  when: result.rc != 0

- name: python3.5インストール可否チェック
  shell: bash -lc "conda info -e | grep 'python3.5'"
  register: result
  failed_when: result.rc not in [0, 1]

- name: python3.5インストール
  shell: bash -lc "conda create -n python3.5 python=3.5 anaconda -y"
  when: result.rc != 0
