---
- name: bash_profileの作成
  args:
    creates: ~/.bash_profile
  shell: touch ~/.bash_profile
  
- name: pyenvをインストール
  args:
    creates: ~/.pyenv
  shell: '{{item.cmd}}'
  with_items:
    - cmd: git clone https://github.com/yyuu/pyenv.git ~/.pyenv
    
- name: pyenv,anaconda設定
  lineinfile:
    dest=~/.bash_profile
    line={{ item }}
  with_items:
    - 'export PYENV_ROOT=~/.pyenv'
    - 'export PATH=$PYENV_ROOT/bin:$PATH'
    - 'eval "$(pyenv init -)"'
    - 'export PATH="$PYENV_ROOT/versions/anaconda3-4.4.0/bin/:$PATH"'

- name: anacondaをインストール
  args:
    creates: ~/.pyenv/versions/anaconda3-4.4.0
  shell: bash -lc "pyenv install anaconda3-4.4.0"
 
- name: anaconda rehash
  args:
    creates: ~/.pyenv/versions/anaconda3-4.4.0
  shell: bash -lc "pyenv rehash"
  
- name: anaconda global
  args:
    creates: ~/.pyenv/versions/anaconda3-4.4.0
  shell: bash -lc "pyenv global anaconda3-4.4.0"
  
- name: anaconda update
  args:
    creates: ~/.pyenv/versions/anaconda3-4.4.0
  shell: bash -lc "conda update conda"
