---
- name: install basic pkg
  apt: name={{item}} state=installed update_cache=yes
  become: yes
  with_items:
  - mecab
  - libmecab-dev
  - mecab-ipadic
  - mecab-ipadic-utf8

- name: neologdのダウンロード
  args:
    creates: ~/mecab-ipadic-neologd
  shell: git clone https://github.com/neologd/mecab-ipadic-neologd.git
  
- name: neologdのインストール
  args:
    creates: /usr/local/lib/mecab/dic/mecab-ipadic-neologd
  become: yes
  shell: '{{item.cmd}}'
  with_items:
    - cmd: cd mecab-ipadic-neologd && bin/install-mecab-ipadic-neologd -n -y

- name: neologdの削除
  file:
    state: absent
    path: '{{ item }}'
  become: yes
  with_items:
    - ~/mecab-ipadic-neologd
