---
- name: install basic pkg
  apt: name={{item}} state=installed update_cache=yes
  become: yes
  with_items:
  - vim
  - git
  - zsh
  - zip
  - ubuntu-desktop
  - build-essential
  - make
  - ubuntu-make