---
- hosts: develop
  roles:
    - { role: package }
    - { role: common }
    - { role: develop }

- hosts: develop
  become: yes
  roles:
    - { role: cmprescott.chrome}
    - { role: tersmitten.pycharm }
    - { role: ansible-clion }
